apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test3
    app.kubernetes.io/part-of: test3
  name: test3237t
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test3
    weight: 100
status: {}
