apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test3
    app.kubernetes.io/part-of: test3
  name: test3
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: test3
status:
  loadBalancer: {}
